### ISSUE TITLE
feat module: rate limiter

### ISSUE THREAD

**Issue by Supremesource** [agicommies/communex#27]
# TASKS

- [x] Cli improvement: make process automatically run on the background (pm2 managed), user can specify a flag to run on foreground. Make sure that `--help` specifies very explicitly how to pass the path of the module. I.e format `folder.file.Class`
- [x] Rate limiter that @gabrielcipriano made. So we avoid DDOS attacks.
- [x] Make sure that the client that is calling the api is registered on the network. 
- [x] Ability to blacklist certain calling keys.
- [x] Ability to whitelist certain calling keys. (when used, other keys by default blacklisted)
